# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_dp <- function(alpha, nCluster, pointsPerCluster, ClusterLabel, alphaPrior, parPrior, data, mu, sigma, predArray, nrun) {
    .Call('_Rmap2batch_rcpp_dp', PACKAGE = 'Rmap2batch', alpha, nCluster, pointsPerCluster, ClusterLabel, alphaPrior, parPrior, data, mu, sigma, predArray, nrun)
}

